import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState} from 'react';
import { equal } from 'assert';

export default function Home() {

  const [calc, setCalc] = useState('');
  const [result, setResult] = useState('');
  const operators = ['/', '*', '+', '-', '.'];

  function equalTo() {
    setCalc(eval(calc).toString())
  };

  function deleteLast() {
    if (calc == '') {
      return
    } 
    let value = calc.slice(0, -1)
    setCalc(value)
  }

  // Creating digits from 1-9
  function createDigits() {
    let numbers = [];
    for (let i = 1; i < 10 ; i++) {
      numbers.push(<button onClick={() => newCalc(i.toString())} key={i}>{i}</button>)
    }
    return numbers
  };
  // A function blocking the user from putting two operators together
  function newCalc(value) {
    if (operators.includes(value) && calc === '' || operators.includes(value) && operators.includes(calc.slice(-1))) {
      return;
    }
    setCalc(calc + value)
    // to handle the calculation
    if (!operators.includes(value)) {
      setResult(eval(calc + value).toString())
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.calculator}>
          <div className={styles.screen}>
            {result ? <span>({result})&nbsp;&nbsp;</span> : ''} {calc || '0'}
          </div>
          <div className={styles.operators}>
            <button onClick={() => newCalc('/')}>/</button>
            <button onClick={() => newCalc('*')}>*</button>
            <button onClick={() => newCalc('+')}>+</button>
            <button onClick={() => newCalc('-')}>-</button>  
            <button onClick={deleteLast}>DEL</button>
          </div>
          <div className={styles.numbers}>
            {createDigits()}
          </div>
          <div className={styles.operatorstwo}>
            <button onClick={() => newCalc('0')}>0</button>
            <button onClick={() => newCalc('.')}>.</button>
            <button onClick={equalTo}>=</button>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <p>Built by anguscg</p>
      </footer>
    </div>
  )
}

